/*
* This file is automatically generated and will be overridden when running the build process.
* Generated on: 12/7/2025, 12:57:51 PM
*/

export interface QuizPage {
  id: string;
  name: string;
  quizzes: QuizComponent[];
}

export interface QuizComponent {
  id: string | null;
  name: string;
  src?: string | null;   // <-- new field
}

export const quizPages: QuizPage[] = [
  {
    "id": "docs-example-exam",
    "name": "example-exam",
    "quizzes": [
      {
        "id": "example-exam#example",
        "name": "Example",
        "src": "Example.md"
      }
    ]
  }
];
