import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {
      type: 'link',
      label: 'Download Syllabus PDF',
      href: '/robotframework-RFCP-syllabus/pdfs/RFCP-Syllabus-__VERSION__.pdf',
      customProps: {download: true},
    },
  ],
};

export default sidebars;
